---

- name: Launch EC2
  hosts: localhost
  gather_facts: False
  vars:
    keypair: mykeypairname
    vpc_id: vpc-xxxxxxxx
    subnet_id: subnet-xxxxxxxx
    hosted_zone : myhostedzone.com
    friendly_cidr: 10.10.10.10/32
    hostname:  ansichefjenkins
    instance_type: t2.small
    ami_id: ami-60b6c60a
    region: us-east-1
  tasks:
    - name: Create security group
      ec2_group: 
        name: "{{ hostname }}_group"
        description: ansichef demo
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{ friendly_cidr }}"
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: "{{ friendly_cidr }}"
      register: ec2group
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: "{{ hostname }}_group"
         instance_type: "{{ instance_type }}"
         image: "{{ ami_id }}"
         exact_count: 1
         count_tag: Name
         instance_tags:
            Name: ansichef demo
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet_id }}"
         assign_public_ip: yes
      register: ec2
    - name: Register Route53 Host
      route53: command=create zone="{{ hosted_zone }}" record="{{ hostname }}.{{ hosted_zone }}" type=A value="{{ item.public_ip }}"
      with_items: ec2.instances
    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name:  Vendor with Berks
  hosts: localhost
  gather_facts: False
  vars: 
    local_workspace: "/tmp/ansible_berks_scratch"
  tasks:
    - file: path={{local_workspace}}/chef_repo state=directory mode=0755
    - copy: src=Berksfile dest={{ local_workspace }}/chef_repo/Berksfile 
    - command: berks vendor chdir={{local_workspace}}/chef_repo
      
- name:  Chef Converge with Jenkins
  hosts: launched
  remote_user: ec2-user
  sudo: yes
  vars: 
    local_workspace: "/tmp/ansible_berks_scratch"
  tasks:
    - file: path=/etc/chef state=directory mode=0755 
    - copy: src={{local_workspace}}/chef_repo/berks-cookbooks/ dest=/etc/chef/chef_repo/cookbooks/
    - shell: "curl -L https://www.opscode.com/chef/install.sh|bash && cd /etc/chef/chef_repo && chef-client -z -r \"recipe[jenkins::master]\""
