---

- name: Launch EC2
  hosts: localhost
  gather_facts: False
  vars:
    keypair: garver_aws_key
    instance_type: t2.small
    vpc_id: vpc-882f8ded
    ami_id: ami-60b6c60a
    region: us-east-1
    subnet_id: subnet-860a06ae
  tasks:
    - name: Create security group
      ec2_group: 
        name: ansichef_group
        description: ansichef demo
        vpc_id: "{{ vpc_id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 8080
            to_port: 8080
            cidr_ip: 0.0.0.0/0
      register: ec2group
    - name: Launch instance
      ec2:
         key_name: "{{ keypair }}"
         group: ansichef_group
         instance_type: "{{ instance_type }}"
         image: "{{ ami_id }}"
         exact_count: 1
         count_tag: Name
         instance_tags:
            Name: ansichef demo
         wait: true
         region: "{{ region }}"
         vpc_subnet_id: "{{ subnet_id }}"
         assign_public_ip: yes
      register: ec2
    - name: Register Route53 Host
      route53: command=create zone=aws.alangarver.com record=jenkins.aws.alangarver.com type=A value="{{ item.public_ip }}"
      with_items: ec2.instances
    - name: Add new instance to host group
      add_host: hostname={{ item.public_ip }} groupname=launched
      with_items: ec2.instances
    - name: Wait for SSH to come up
      wait_for: host={{ item.public_dns_name }} port=22 delay=60 timeout=320 state=started
      with_items: ec2.instances

- name:  Vendor with Berks
  hosts: localhost
  gather_facts: False
  vars: 
    scratch_space: "/tmp/ansible_berks_scratch"
  tasks:
    - file: path={{scratch_space}}/chef_repo state=directory mode=0755
    - copy: src=Berksfile dest={{ scratch_space }}/chef_repo/Berksfile 
    - command: berks vendor chdir={{scratch_space}}/chef_repo
      
- name:  Chef Converge with Jenkins
  hosts: launched
  remote_user: ec2-user
  sudo: yes
  vars: 
    scratch_space: "/tmp/ansible_berks_scratch"
  tasks:
    - file: path=/etc/chef state=directory mode=0755 
    - copy: src={{scratch_space}}/chef_repo/berks-cookbooks/ dest=/etc/chef/chef_repo/cookbooks/
    - shell: "curl -L https://www.opscode.com/chef/install.sh|bash"
    - shell: "cd /etc/chef/chef_repo && chef-client -z -r \"recipe[jenkins::master]\""
